### ISSUE TITLE
Encoder issue

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#10]
Pag human ug encode sa request dle na ka cater ug lain nga request kay mo balik sa katong last nga gi encode.... 
![img20180220165257](https://user-images.githubusercontent.com/36658505/36414848-b33cc5c8-165e-11e8-82da-12357e0e68e6.jpg)

**Comment by marktabz** [comment]
bisan pag e click nako na tanan button dha. dle mawala... dle ko ka kitag bagong inug encode...

**Comment by awooo-ph** [comment]
akong i-check, mobalik man ta na sa katong page paghuman ug login.
