### ISSUE TITLE
Dle ma close ang ENCODER nga application kinahanglan pa ehh end task..

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#15]

**Comment by awooo-ph** [comment]
Dili man unta na pwede i-close. Himuan ra nako ang server maka-close sa encoders.

**Comment by awooo-ph** [comment]
mo-logout siya. maka-login ra laing encoder.

**Comment by awooo-ph** [comment]
kung lain mogamit unya dili mag "encode" dili na pwede kay enrollment period man unya ang computer na assign as encoding station.

**Comment by marktabz** [comment]
ok pud sir,,, hehehehe kana nlang sa SERVER nlang e close...
