### ISSUE TITLE
sir ug mag add mig second semester kay mo sumpay ra sya sa first semester,,, dle sya separated... 

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#23]

**Comment by awooo-ph** [comment]
ako ra sulayan ug group. pero ang year level ug semester sa subjects kay dili kinahanglan sa inyong system. para ra unya nas evaluation. dili man pud ta ka-filter kung maka-enrol ba ang student ana na subject bac sa year level ug semester kay wala may evaluation. maka-filter ra base sa course.

**Comment by awooo-ph** [comment]
sa students, butangan nakog ongoing ug year level.
