### ISSUE TITLE
ug mag add mig subject sa lain  nga course mag ipon tanan nga subject sa uban nga course...

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#24]

**Comment by awooo-ph** [comment]
ma-filter man nimo by course.

**Comment by marktabz** [comment]
pwedeg naay ali? kanang morag nalain sya hehehehe.... OK RAKA SIR? daghana nman oiii hehehe

**Comment by awooo-ph** [comment]
maglisod tag group ana kay naa man ubang subjects na naa sa lain-laing course.

**Comment by awooo-ph** [comment]
i-click ng 3 ka dot sa upper right..ma-filter nimo by course
