### ISSUE TITLE
ug mag delete ug subject sa prospectus dle auto delete sa subject nga table, manual pa nga e delete.... hehehe

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#25]

**Comment by awooo-ph** [comment]
Sakto ra na siya kay ang naa sa list of subjects kay tanan man na subjects. Example: ang courses na BSBS ug BSCS pareho naay ENG0 na subject. Kung pag-delete nimo sa ENG0 sa BSBS ma-delete pud sa SUBJECTS, ang ENG0 sa BSCS mawala pud.

**Comment by awooo-ph** [comment]
Ako lang himuan na kung wala nay course na naa ang usa ka subject..dili na siya makita sa list of subjects.
