### ISSUE TITLE
sir ug naay password ang wifi sa akong wifi (WPA2 PSK) dle maka login ang encoder ug android... hehehe

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#27]

**Comment by awooo-ph** [comment]
i-check kung maka-ping ra ba ang server sa android ug encoder.

**Comment by marktabz** [comment]
huo sir ma ping lang... tanan ma ping lang pero dle mo login... login failed man... hehehehe

**Comment by marktabz** [comment]
aiiii dle diay ma ping sir hehehehe sorry...

**Comment by awooo-ph** [comment]
murag sa multicast na..gamit sa system para dili na kinahanglan i-input ang ip sa server. dili cguro allowed basta secured and AP. unsa may router gamit nimo?

**Comment by awooo-ph** [comment]
aw..sa phone na. sa ubang router ma-enable/disable man nimo ang multicast. sa android murag dili cguro. i-close ra nako ni kay sa router na issue man ni.
