### ISSUE TITLE
Logout button sa android para sa uban nga ganahan maki-login lang sa kauban kay wla CP... hehehe

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#30]

**Comment by awooo-ph** [comment]
i-close ra ang app. auto-logout na. pero cge himuan lang. hehe

**Comment by marktabz** [comment]
dont mined na ani sir... ok nato... hehehehe

**Comment by marktabz** [comment]
close lang ni,,, dle ni importante anyway auto logout mn pd sya...

**Comment by awooo-ph** [comment]
ok..naglibog pud ko asa dapit ibutang.
