### ISSUE TITLE
walay cancel button para sa encoder what if na click niya ang request dayun for example ga error ang server or dle sya mo padayun ug encode.... hehehehe

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#34]

**Comment by awooo-ph** [comment]
nganung dili man mopadayon? pahibal-on ng encoders na ug naka-sugod nag process..dili pwede i-cancel. bac pang-cancellon ng dili niya ganahan or naay gipaabot na request. pero unsa may lantaw ninyo?

kung mo-crush ang server, wala nay mahimo ang tanang clients. mao ng i-test taman before production. dili na pud ka-send ug cancellation ng encoder kung wala nay server.
