### ISSUE TITLE
walay cancel button para sa schedule nga na click sa student for example usbon niya iya nga time schedule... hehehehe

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#38]

**Comment by awooo-ph** [comment]
makausab ra man ang student sa iyang schedule. sample ENG0 MWF 1-2 iyang na-enrollan. search ra siya'g lain schedule sa ENG0..ma-replace ra na dritso. pero kung na-submit na niya..i-cancel sa niya usa sya ka-change schedules. gituyo gihapon kay kung maka-change siya bisan na-submit na..pwede man siya mo-submit dayon bisan wala pa kahuman para mauna sa linya.

**Comment by awooo-ph** [comment]
maka-delete na ang student ug class schedule. i-long press lang
