### ISSUE TITLE
bisag ma delete ang request sa student sa Enrollment request Tab sa server,,,,, kay makita ra sa encoder app ang na delete nga request,,, unya kay wla may cancel button accept nako mo logout nuan sya, dayun dle na mo login restart npud,,, second attempt pag login nako click nako ang mo cater ug request ni force stop na ang server.... hehehehe 

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#39]

**Comment by awooo-ph** [comment]
ako ni i-check. dili na man unta na makita sa encoder ang na-delete na na request. ang sa server, delete all request ra ang naa kay para pag-start sa enrollment. kung nakasugod nag dawat ug request..dili maayo na maka-delete ug individual requests. kung nasayop ang student..pwede niya i-cancel.

ang encoder gituyo na na dili ka-cancel kung nakasugod na siya'g process ug request kay bac i-skip niya ang uban..mawalay pulos ang pasunod.
