### ISSUE TITLE
in this case nga ma view sa encoder ang deleted nga request mka send na ug daghan nga request ang usa ka student.. so 1 student can have many request... hehehehe

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#41]
![image](https://user-images.githubusercontent.com/36658505/36553870-71a86014-1838-11e8-95b4-c59bd7bbad38.png)

**Comment by awooo-ph** [comment]
sa server man na..ang encoder dili ka view sa list of requests. maka-process ra sya'g one request at a time. ang students pud dili makapa-encode ug daghan. usa ra ka request per student id ug or.
