### ISSUE TITLE
dapat mo notify sa student nga conflict or na closan syag time,,, OR mas best kung pwede sila maka message between sa ni encode ug sa student nga naay issue sa sched. para mas dali... :) hehehehehehe

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#43]

**Comment by awooo-ph** [comment]
pwede man..mao pud na unang plano. pero ang downside ana kay malangay ang encoder. mas maayo kung dili na maghulat ang encoder sa student. kung naay conflict or na close sa subjects..bisan usa ra i-close sa encoder dayon submit. maka-process na dayon sya'g laing request. malangay cguro ang affected student pero ang uban mas mapaspas.

ang naa ron, ang student mo-request ug update through clicking sa queue number or pag-login niya'g usab. pwede nato himuan na mo-push ug notification sa student kung na-process na iyang request..either accepted or failed.
