### ISSUE TITLE
bisag puno na ang slots sa schedule ma click ra jpun sa student...

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#47]

**Comment by awooo-ph** [comment]
gituyo ra na kay ang encoder ra jud mo-close. bac d i modawat rag students ag instructor bisan sobra nas 50. dili man official ng schedule ani na program. dili pud ta ka-sync old system. pero himoan nato nig option na auto-close or manual.

**Comment by marktabz** [comment]
sa old system nila ela rman padak.an ang slots what if mo dawat ra ang instructor ug daghan...
