### ISSUE TITLE
daghan kaayu receipts info nga mogawas sa encoder app,,, dle maglibog ang encoder ani kung unsay tinood? hehehehe

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#56]
![image](https://user-images.githubusercontent.com/36658505/36634153-32e66746-19db-11e8-9412-e6ef67504825.png)

**Comment by awooo-ph** [comment]
kung mao na tanan gi-input ni LotcheCabase..mao pud nay i-input sa encoder. pero nganong nagtapot man ng firstname ug lastname?

**Comment by marktabz** [comment]
hahahaha wla ko kabalo nganong ga tapot... try ko lain account

**Comment by marktabz** [comment]
mag tapot jud ang first ug last name sir hehehe

**Comment by awooo-ph** [comment]
himuan natog setting para max number of receipts.
