### ISSUE TITLE
feel nako mas nindot ug naay minimize button ang encoder app kay pariho anah mag lisod kog navigate kay na tabonan hehehe PICTURE BELOW....

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#57]
![image](https://user-images.githubusercontent.com/36658505/36634216-199eb0bc-19dc-11e8-9d11-4befa204196a.png)

**Comment by awooo-ph** [comment]
hehe..pwede pud. pero dili man na makatabon sa work sa encoder. himuan lang pud nig option sa server. apil pud ang close.
