### ISSUE TITLE
ang encoder nga app kay ug mag handle sila ug request sa INFO ug sa RECEIPTS tab kay naa ang accept, conflict ug closed nga buttons apil ang accept which is necessary lang sa subject nga tab... hehehehe

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#60]

**Comment by awooo-ph** [comment]
ilisan lang nato ug CANCEL na button na sila. naa man pud accept/conflict/close kada subject. para pud naay kabutangan sa cancel button. para ma-close ang #34

**Comment by marktabz** [comment]
ok orayt sir ikaw ang bahala pd hehehe
