### ISSUE TITLE
pwede ma doble ang na enroll nga studyante sa server... possible sya what if naay mag pa enroll sa lahi2x nga encoder basig TRIP lang niya bah hehehehe

### ISSUE THREAD

**Issue by marktabz** [awooo-ph/EncodeMe#62]

**Comment by marktabz** [comment]
ahhh ok sir... ma hitabo ra diay na pag lahi siya ug ID NUMBER hehehe nalimot ko.. sorry close lng nahhh

**Comment by awooo-ph** [comment]
hehe..student id gi-check. ang name wala ra. pero pwede pud dili pwede maka-enroll basta pareha ug first name, last name ug middle name.

**Comment by marktabz** [comment]
aiii dle pwede sir kay daghan mn kapariho pangalan ug apelyedo hehehehe

**Comment by awooo-ph** [comment]
aw..mao pud
